<<<<<<< HEAD
const crash = (reason) => {
  process.on(reason, (err) => {
    console.error(reason, err.stack)
    process.exit(-1)
  })
}

crash('unhandledRejection')
crash('uncaughtError')
crash('warning')
=======
const crash = (reason) => {
  process.on(reason, (err) => {
    console.error(reason, err.stack)
    process.exit(-1)
  })
}

crash('unhandledRejection')
crash('uncaughtError')
crash('warning')
>>>>>>> 6dd80b73d9d1419f981ad90206a77a31f421b3ec
